services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./public:/var/www/public
      - ./storage:/var/www/storage
    ports:
      - "8874:80"
    container_name: app_nginx
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: project_app
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: smartblax
      POSTGRES_DB: smartblax
      POSTGRES_USER: smartblax
    ports:
      - "5432:5432"
    container_name: app_db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
